# Generated by Django 4.0.3 on 2022-07-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_completed_workout'),
        ('users', '0002_user_heart'),
    ]

    operations = [
    ]
