# Generated by Django 4.0.3 on 2022-08-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_coins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completed_workout",
            name="user",
        ),
        migrations.AddField(
            model_name="completed_workout",
            name="workout_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
