# Generated by Django 4.0.3 on 2022-07-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_completed_workout_0002_user_heart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='heart',
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
