# Generated by Django 4.0.3 on 2022-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed_workout',
            name='user',
        ),
        migrations.AddField(
            model_name='completed_workout',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
