# FROM python:3
# RUN python -m pip install --upgrade pip
# ENV PYTHONUNBUFFERED 1
# WORKDIR /app
# COPY requirements.txt requirements.txt
# RUN pip install -r requirements.txt
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# RUN chmod a+r /docker-entrypoint-initdb.d/*

FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /deps
COPY requirements.txt requirements.txt
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD /wait && uvicorn main:app --reload --host 0.0.0.0